# This is a basic workflow that is manually triggered
- name: Build
  run: gcc -Wall -Wextra -Werror -O2 src/hello.c -o hello

- name: Test
  run: output="$(./hello)"
       test "$output" = "Hello world!"
